# rabbitmq-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      name: rabbitmq
      port: 5672
    - protocol: TCP
      name: rabbitmq-management
      port: 15672
  type: ClusterIP
