apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
    - protocol: TCP
      port: 15672
      targetPort: 15672
  type: NodePort


# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq-exporter-service
# spec:
#   selector:
#     app: rabbitmq-exporter
#   ports:
#     - protocol: TCP
#       port: 9090
#       targetPort: 9090
#   type: NodePort
