apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter-service
spec:
  selector:
    app: rabbitmq-exporter
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort
